=== AckywOw/JavaWeb/web/WEB-INF/dtd/books.dtd
<?xml version="1.0" encoding="UTF-8"?>
        <!ENTITY % content "(name|bookname),author,price">

        <!ELEMENT books (book*)>
        <!ELEMENT book (%content;)>

        <!ELEMENT name (#PCDATA)>
        <!ELEMENT author (#PCDATA)>
        <!ELEMENT price (#PCDATA)>
        <!ELEMENT bookname (#PCDATA)>

        <!ATTLIST book
                id CDATA #FIXED "a1"
                haha CDATA #REQUIRED
                hehe CDATA #IMPLIED
                >

        <!--现在的浏览器不支持外部引用实体-->
        <!ENTITY ads "你好">

=== AckywOw/JavaWeb/web/WEB-INF/dtd/books.xml
<?xml version="1.0" encoding="utf-8" ?>
<!--<!DOCTYPE books [-->
<!--<!ELEMENT books (book*)>-->
<!--<!ELEMENT book ((name|bookname) ,author,price)>-->

<!--<!ELEMENT name (#PCDATA)>-->
<!--<!ELEMENT author (#PCDATA)>-->
<!--<!ELEMENT price (#PCDATA)>-->
<!--<!ELEMENT bookname (#PCDATA)>-->

<!--<!ATTLIST book-->
<!--id CDATA #FIXED "a1"-->
<!--haha CDATA #REQUIRED-->
<!--hehe CDATA #IMPLIED-->
<!--&gt;-->

<!--<!ENTITY ads "你好">-->
<!--]>-->
<!DOCTYPE books SYSTEM "books.dtd">
<books>
    <book id="a1" haha="a2">
        <name>&ads;</name>
        <author></author>
        <price></price>
    </book>


    <book id="a1" haha="a3">
        <bookname>&ads;</bookname>
        <author></author>
        <price></price>
    </book>

</books>
