=== AckywOw/JavaWeb/web/WEB-INF/schema/books.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema"
        targetNamespace="http://sas.co"
        elementFormDefault="qualified"
        attributeFormDefault="unqualified"
>
    <element name='books'>
        <complexType>
            <sequence maxOccurs="2">
                <element name='book'>
                    <complexType>
                        <sequence>
                            <element name="name" type="string"/>
                            <element name="author" type="string"/>
                            <element name="price" type="integer"/>
                            <element name="type" type="string"/>

                        </sequence>
                        <attribute name="id" type="integer" use="required"/>
                        <attribute name="lang" type="double" use="required"/>
                        <attribute name="haha" type="string"/>
                    </complexType>
                </element>
            </sequence>
        </complexType>
    </element>
</schema>

=== AckywOw/JavaWeb/web/WEB-INF/schema/books.xml
<?xml version="1.0" encoding="utf-8"?>

<books xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns="http://sas.co"
       xsi:schemaLocation="http://sas.co books.xsd">
  <book id="1" lang="0.01">
    <name>asda</name>
    <author/>
    <price>33</price>
    <type>xxxx</type>
  </book>
  <book id="2" haha="a3" lang="1.01">
    <name>dsa</name>
    <author>liubei</author>
    <price>100</price>
    <type>xxxx</type>
  </book>
</books>
